### ISSUE TITLE
Ability to filter by [Channel]

### ISSUE THREAD

**Issue by AldeRoberge** [needle-tools/needle-console#20]
It would be great to be able to filter like this :

            Debug.Log($"[Setup] Setting current setup to {setupInfo.Type.Name}.");

And then in the editor console :

![image](https://user-images.githubusercontent.com/4276275/234736692-4275bffb-81d4-407d-bd01-1892541803f9.png)

**Comment by TheXRMonk** [comment]
@marwie 
Pinging this since I can't seem to find the "Channels" dropdown - where is it? I'm on latest UPM package.
I have the same use case as OP.

**Comment by marwie** [comment]
The channels dropdown is something the OP asked about but it's not a feature of the console here
See my previous response - you can try adding it as a custom filter in your own code

**Comment by TheXRMonk** [comment]
Actually, the ConsoleFilterPreset might be what I was looking for. Too bad this isn't apparent in the readme.

This way we can quickly share package or namespace filters across our whole team, although it's a bit sad you have to "capture" the logs in the editor before you can filter them instead of just defining them up front.
Guess I could look into adding that feature myself.

**Comment by TheXRMonk** [comment]
> Yes and feel free to make a PR and/or update the readme if you think information is missing or could be more clear

[PR](https://github.com/needle-tools/needle-console/pull/23) for namespace filters
